apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-app-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath   # Correctly reference the StorageClass

